# Generated by Django 3.1.6 on 2021-02-15 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fighters', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fighter',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
