# Generated by Django 3.1.6 on 2021-02-15 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fighters', '0002_fighter_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fighter',
            name='image',
            field=models.ImageField(null=True, upload_to='photos'),
        ),
    ]
